#CREAR DOCKERS  SOLO DE DJANGO
version: '3.5'
services:
  api_django:
    build: ./api_django
    command: python api_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_django_dir
    ports:
      - "8000:8000"
  app:
    build: ./react-app
    command: npm start
    volumes:

      - ./react-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api_django
    tty: true
